title: Aidan 的博客
email: aidan@example.com
description: >-
  记录课程学习、实验过程与技术探索，做一个持续成长的计算机专业学生。
baseurl: ""
url: "https://aidan0712.github.io"
twitter_username: aidan0712
github_username: Aidan0712
author: Aidan

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - about.md

social_links:
  github: Aidan0712
  twitter: aidan0712
